### ISSUE TITLE
Thank you and share some thoughts

### ISSUE THREAD

**Issue by vyemialyanchyk** [g4lb/camera-recorder-with-human-detection#1]
I would say this is practically not workable solution...
1,730,662 bytes video file which is 34 secs long takes minutes to generate some output ~10 minutes on 100% 4.66 GHz CPU.. but was an interesting gameplay, thank you!

**Comment by g4lb** [comment]
Dear @vyemialyanchyk,
Thanks for letting me know, try to reduce frame size and frame rate, soon I'll release a new updated code
